### ISSUE TITLE
Bounds on `std::error::Error` implementation for `ParseError<P>` too restrictive

### ISSUE THREAD

**Issue by bsteinb** [Marwes/parser-combinators#33]
Commit 1e500c6efa1dab4b3e5fc883900a401228053d89 changed the bounds on the implementation of `std::error::Error` for `ParseError<P>`. It now requires, among others, `P::Position: Positioner` which I think is unnecessarily restrictive and in fact not the case for existing instances of `P`, e.g. `char` and `u8`.

**Comment by Marwes** [comment]
Thanks for noticing the typo.

Fixed in 7f86f3b3d7079590b6eb258a7bf8a66c4d845b19

**Comment by Marwes** [comment]
And I will publish 0.5.1 once travis finishes testing.
