### ISSUE TITLE
Unable to use vector as stream

### ISSUE THREAD

**Issue by nikklassen** [Marwes/parser-combinators#34]
I am using my own type ```Token``` as the item for my parser, with a type AST as the output.  Token has a TokenPositioner which is an exact copy of BytePositioner.  I have a top level parser with the signature
```rust
fn command<I>(input: State<I>) -> ParseResult<AST, I, Token> where I: Stream<Item=Token>
```
when I try to use this as a parser on a Vec\<Token\> named ```tokens``` like so
```rust
parser(command).parse(from_iter(tokens.iter()))
```
It prints the error
```
src/lexer.rs:127:21: 127:52 error: type mismatch resolving `<parser_combinators::primitives::IteratorStream<core::slice::Iter<'_, tokenizer::Token>> as parser_combinators::primitives::Stream>::Item == tokenizer::Token`:
 expected &-ptr,
    found enum `tokenizer::Token` [E0271]
src/lexer.rs:127     parser(command).parse(from_iter(tokens.iter()))
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/lexer.rs:127:21: 127:52 help: run `rustc --explain E0271` to see a detailed explanation
```

Any advice you can offer would be helpful.  Thanks.

**Comment by Marwes** [comment]
Vec::iter (really [slice::Iter](https://doc.rust-lang.org/nightly/std/slice/struct.Iter.html)) returns `&Token` items while your command method returns `Token`. It should work by calling cloned on the iterator (`tokens.iter().cloned()`)

**Comment by nikklassen** [comment]
Thanks!  I thought this might be the problem, but I had tried using into_iter()

**Comment by Marwes** [comment]
For future reference, `Vec::into_iter` returns the correct type but that iterator does not implement `Clone` which is necessary for using iterators.
