### ISSUE TITLE
Having trouble making recursive parsers

### ISSUE THREAD

**Issue by Ralle** [Marwes/parser-combinators#36]
I am building a parser for a language of my imagination, I am having problem with recursive parsers. Take a look at this gist:

https://gist.github.com/Ralle/336941d1472a598d1121

I can parse ints and I can parse floats, but as soon as I make a pair using '(int, int)' it expects a float. I don't understand why this happens. I tried switching around the int_parser and float_parser but then it would obviously not parse floats as it succesfully parses the int and then don't know what to do with the '.'.

Please advice.

**Comment by Marwes** [comment]
The parsers are LL(1) which means that in your or parser the float parser
being first manages to parse a few digits before failing when it does not
fund a '.'. You can create parsers with arbitrary lookahead with the try
function.

**Comment by Ralle** [comment]
Ah. I never knew what that meant. Thank you so much for helping me and for responding so quickly.

**Comment by Marwes** [comment]
As an aside I also have the language extension crate at https://github.com/Marwes/parser-combinators-language. Its a bit rough but there might be something of use for you there.
